name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-20.04

    env:
        DEBIAN_FRONTEND: "noninteractive"
        CONAN_USER_HOME: "${{ github.workspace }}/"
        CONAN_NON_INTERACTIVE: 1
        blixt_conan_path: "$HOME/.local/bin"

    steps:
      - uses: actions/checkout@v2

      - name: Update environment
        shell: bash
        run: |
          # Update package lists
          sudo apt update -qq
          # Install build tools
          sudo apt install -y \
            make \
            cmake \
            curl \
            libgl1-mesa-dev \
            libx11-dev \
            libx11-xcb-dev \
            libxcb-dri3-dev \
            libxcb-icccm4-dev \
            libxcb-image0-dev \
            libxcb-keysyms1-dev \
            libxcb-randr0-dev \
            libxcb-render-util0-dev \
            libxcb-render0-dev \
            libxcb-shape0-dev \
            libxcb-sync-dev \
            libxcb-util-dev \
            libxcb-xfixes0-dev \
            libxcb-xinerama0-dev \
            libxcb-xkb-dev \
            lld \
            ninja-build \
            pkg-config \
            python3 \
            python3-pip \
            xkb-data \
            xorg-dev

          pip3 install wheel setuptools
          pip3 install conan mako

      - name: Configure CMake
        shell: bash
        run: |
          export PATH="${{ env.blixt_conan_path }}":$PATH

          # Setup conan
          # Note: libstdc++11 is needed to use new libc++ ABI
          conan profile new default --detect
          conan profile update settings.compiler.libcxx=libstdc++11 default
         

      - name: Build
        run: make debug

