name: WINDOWS

on: [push, pull_request]

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
        - uses: actions/checkout@v2
        - uses: ilammy/msvc-dev-cmd@v1
        - uses: actions/setup-python@v2
          with:
              python-version: '3.8'

        - name: Install Qt6
          shell: cmd
          run: |
            pip install aqtinstall
            setup.bat
            echo "${{ github.workspace }}/Qt/%QTVERSION%/msvc2019_64/bin/" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
            echo "Qt6_DIR=%Qt6_DIR%" >> $GITHUB_ENV

        - name: Build
          shell: cmd
          run: |
            build_release.bat

        - name: Create Zip Archive
          shell: cmd
          run: |
            pack.bat

        - name: Windows Release
          uses: actions/upload-artifact@v1
          with:
              name: WindowsBuild
              path: C:\zero-controller.zip
