name: WINDOWS

on: [push, pull_request]

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
        - uses: actions/checkout@v2
        - uses: ilammy/msvc-dev-cmd@v1
        - uses: actions/setup-python@v2
          with:
              python-version: '3.8'

        - name: Install Qt6
          shell: pwsh
          run: |
            pip install aqtinstall
            .\setup.ps1
            echo 'Qt6_DIR=$Qt6_DIR' >> $env:GITHUB_ENV 
            echo DONE
      
        - name: Build
          shell: pwsh
          run: |
            .\build.bat Release

        - name: Create Zip Archive
          shell: pwsh
          run: |
            .\pack.bat

        - name: Windows Release
          uses: actions/upload-artifact@v1
          with:
              name: WindowsBuild
              path: C:\zero-controller.zip
